repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
    -   repo: https://github.com/psf/black
        rev: 20.8b1
        hooks:
        -   id: black
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.1
        hooks:
        -   id: flake8
            additional_dependencies: [flake8-bugbear]
