name: Tests
on: push
jobs:
  tests-py36:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
        architecture: x64
    - run: pip install poetry
    - run: poetry install -E pandas
    - run: poetry run pytest --cov
    - run: poetry run pytype
  tests-py37:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: x64
    - run: pip install poetry
    - run: poetry install -E pandas
    - run: poetry run pytest --cov
    - run: poetry run pytype
  tests-py38:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: pip install poetry
    - run: poetry install -E pandas
    - run: poetry run pytest --cov
    - run: poetry run pytype
